### ISSUE TITLE
Error:  Cannot cast array data from dtype('O') to dtype('int64') according to the rule 'safe'

### ISSUE THREAD

**Issue by DanBeaton** [genomicsITER/NanoRTax#1]
Hello 

This is my first time trying NanoRTax and am new to nanopore data analysis.  I am getting an error that I don't see how to fix or workaround.  To move past the bottleneck created by the error I can move the related directories out of the work folder.  The error occurs when running the kraken_push process and seems to be related to when the counts are to be tabulated for the diversity calculations.  

Any help is appreciated.

Not sure if this is related but for the read_binning process I had to add the --drop flag.  This error looked to be due to some of the rows in the kraken_report_full that had a value for a count but was otherwise empty -- no information on kingdom, phylum, class, order, family, genus, or species as in the rest of the rows.

Command error:
executor >  local (12)
[d6/648673] process > QC (61)                   [ 14%] 61 of 434, cached: 59
[79/f5a961] process > qc_reporting (33)         [ 55%] 33 of 60, cached: 31
[e3/41d78b] process > read_binning_kraken (60)  [100%] 60 of 60, cached: 58
[b6/4d0d4a] process > agg_kraken (49)           [ 84%] 49 of 58, cached: 46
[52/cba34b] process > kraken_push (24)          [ 52%] 25 of 48, cached: 23, failed: 1
[4e/030042] process > agg_kraken_diversity (23) [100%] 23 of 23, cached: 22
[bc/b73cab] process > output_documentation      [100%] 1 of 1, cached: 1 ✔
Execution cancelled -- Finishing pending tasks before exit
-[nf-core/rtnanopipeline] Pipeline completed with errors-
WARN: There's no process matching config selector: get_software_versions
Error executing process > 'kraken_push (23)'
 
Caused by:
  Process `kraken_push (23)` terminated with an error exit status (1)
 
Command executed [/athena/home/beatond/Tools/NanoRTax/templates/kraken_push.py]:
 
  #!/usr/bin/env python3
 
  import datetime
  import re
  import pandas as pd
  import skbio
 
 
  df = pd.read_csv("kraken_report_full.txt", delimiter="        ", names=['seq_id', 'tax_id', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species'])
  tax_table = df['class'].value_counts()
  tax_table_class = pd.DataFrame(list(zip(tax_table.index.tolist(), tax_table.tolist())), columns =['tax_id', 'read_count'])
  tax_table_class.to_csv("kraken_report_class.csv", header=1, columns=["tax_id", "read_count"], index=False)
 
  tax_table = df['order'].value_counts()
  tax_table_order = pd.DataFrame(list(zip(tax_table.index.tolist(), tax_table.tolist())), columns =['tax_id', 'read_count'])
  tax_table_order.to_csv("kraken_report_order.csv", header=1, columns=["tax_id", "read_count"], index=False)
 
  tax_table = df['family'].value_counts()
  tax_table_family = pd.DataFrame(list(zip(tax_table.index.tolist(), tax_table.tolist())), columns =['tax_id', 'read_count'])
  tax_table_family.to_csv("kraken_report_family.csv", header=1, columns=["tax_id", "read_count"], index=False)
 
  tax_table = df['genus'].value_counts()
  tax_table_genus = pd.DataFrame(list(zip(tax_table.index.tolist(), tax_table.tolist())), columns =['tax_id', 'read_count'])
  tax_table_genus.to_csv("kraken_report_genus.csv", header=1, columns=["tax_id", "read_count"], index=False)
 
  tax_table = df['species'].value_counts()
  tax_table_species = pd.DataFrame(list(zip(tax_table.index.tolist(), tax_table.tolist())), columns =['tax_id', 'read_count'])
  tax_table_species.to_csv("kraken_report_species.csv", header=1, columns=["tax_id", "read_count"], index=False)
 
  shannon = skbio.diversity.alpha.shannon(tax_table_class['read_count'])
  simpson = skbio.diversity.alpha.simpson(tax_table_class['read_count'])
  file1 = open("kraken_diversity_class.csv","w")
  file1.write(str(tax_table_class['read_count'].sum()) + "," + str(round(shannon,3)) + "," + str(round(simpson,3)) + "\n")
  file1.close()
 
  shannon = skbio.diversity.alpha.shannon(tax_table_order['read_count'])
  simpson = skbio.diversity.alpha.simpson(tax_table_order['read_count'])
  file1 = open("kraken_diversity_order.csv","w")
  file1.write(str(tax_table_order['read_count'].sum()) + "," + str(round(shannon,3)) + "," + str(round(simpson,3)) + "\n")
  file1.close()
 
  shannon = skbio.diversity.alpha.shannon(tax_table_family['read_count'])
  simpson = skbio.diversity.alpha.simpson(tax_table_family['read_count'])
  file1 = open("kraken_diversity_family.csv","w")
  file1.write(str(tax_table_family['read_count'].sum()) + "," + str(round(shannon,3)) + "," + str(round(simpson,3)) + "\n")
  file1.close()
 
  shannon = skbio.diversity.alpha.shannon(tax_table_genus['read_count'])
  simpson = skbio.diversity.alpha.simpson(tax_table_genus['read_count'])
  file1 = open("kraken_diversity_genus.csv","w")
  file1.write(str(tax_table_genus['read_count'].sum()) + "," + str(round(shannon,3)) + "," + str(round(simpson,3)) + "\n")
  file1.close()
 
  shannon = skbio.diversity.alpha.shannon(tax_table_species['read_count'])
  simpson = skbio.diversity.alpha.simpson(tax_table_species['read_count'])
  file1 = open("kraken_diversity_species.csv","w")
  file1.write(str(tax_table_species['read_count'].sum()) + "," + str(round(shannon,3)) + "," + str(round(simpson,3)) + "\n")
  file1.close()
 
  #diversity = pd.DataFrame(data={"Shannon index": [round(shannon,3)], "Simpson index": [round(simpson, 3)]})
  #diversity.to_csv("kraken_diversity.csv", sep=',',index=False, header=0)
 
Command exit status:
  1
 
Command output:
  (empty)
 
Command error:
  /athena/home/beatond/Data_analysis/Nanopore_data/crosswise/NanoRTax_test/work/conda/nanortax-8a6750e7c29e704fe98c2ea094c85a6b/lib/python3.6/site-packages/skbio/util/_testing.py:16: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
    import pandas.util.testing as pdt
  Traceback (most recent call last):
    File ".command.sh", line 30, in <module>
      shannon = skbio.diversity.alpha.shannon(tax_table_class['read_count'])
    File "/athena/home/beatond/Data_analysis/Nanopore_data/crosswise/NanoRTax_test/work/conda/nanortax-8a6750e7c29e704fe98c2ea094c85a6b/lib/python3.6/site-packages/skbio/diversity/alpha/_base.py", line 868, in shannon
      counts = _validate_counts_vector(counts)
    File "/athena/home/beatond/Data_analysis/Nanopore_data/crosswise/NanoRTax_test/work/conda/nanortax-8a6750e7c29e704fe98c2ea094c85a6b/lib/python3.6/site-packages/skbio/diversity/_util.py", line 26, in _validate_counts_vector
      counts = counts.astype(int, casting='safe', copy=False)
  TypeError: Cannot cast array data from dtype('O') to dtype('int64') according to the rule 'safe'
 
Work dir:
  /athena/home/beatond/Data_analysis/Nanopore_data/crosswise/NanoRTax_test/work/71/d8b8dda7cc3212135eda44829a8a67
 
Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by DanBeaton** [comment]
Hello -- I have done more digging.  The error described above appears to follow from the conversion of the krkinput.fastq file to the krakenreport.txt file.

kraken_report_annotated_otu.txt has otu information from kingdom to species.
kraken_report_annotated.txt only has  information to the level of kingdom.

The diversity analysis in kraken_push.py starts that the level of class so the report files have no data to analyze and create the the diversity files.

The seqid for the first taxon id in the list is shown in the file to be on row 2 rather than row 1.

Any suggestions on how to fix or workaround and see if it occurs in other qced.fastq files in the sequencing run?

**Comment by DanBeaton** [comment]
After much looking, the issue here is with the fats5 conversion to fastq.
